### ISSUE TITLE
The Question Collection Nickname Attribute - Does it exist?

### ISSUE THREAD

**Issue by atguser** [bcemmett/SurveyMonkeyApi-v3#51]
We were hoping to use the Nickname attribute of the SurveyMonkeyAPI-v3 Question collection to record question numbers.  Unfortunately, we don't see any reference to this attribute in the SM API docs and don't see a way to set it from the SM web UI.   Is Nickname part of the Question object in error?  If so, it should probably be pulled from Question.  If not, do you have any advice on how to set the value?

**Comment by bcemmett** [comment]
Images can be added to surveys as if they were questions for presentational reasons. There's no user response, but the api still returns them as Question objects. Images can have a nickname to them (see the screenshot) and that gets returned in the api as the Nickname property. So basically it's only available on Images. I've no idea why it's that way, but since the property's available it should be exposed, even though for most question types it will just be null.

You can see this happen in the data processing tests. https://github.com/bcemmett/SurveyMonkeyApi-v3/blob/master/SurveyMonkeyTests/DataProcessingTests.cs#L16 is a real response for a survey structure which includes a large variety of question types / structures. One is an image, and includes the Nickname property. I only noticed the property exists at all because https://github.com/bcemmett/SurveyMonkeyApi-v3/blob/master/SurveyMonkey/TolerantJsonConverter.cs#L136 is designed to catch that sort of undocumented property when in debug mode - their documentation is, shall we say, incomplete...

![image](https://cloud.githubusercontent.com/assets/4490719/24921747/c3d97642-1ee3-11e7-9681-566cbd82abd5.png)

Cheers!
Ben

**Comment by atguser** [comment]
Thanks for the clarification.  I don’t think I’d ever have figured that one out!

**Comment by atguser** [comment]
Leave a comment
