### ISSUE TITLE
An error occurs when the postman command is used to modify the controller. Procedure

### ISSUE THREAD

**Issue by dickens1998** [bcemmett/SurveyMonkeyApi-v3#97]
I use method calls to modify controller errors according to Postman and turn on the corresponding permissions in my application.

**Comment by dickens1998** [comment]
![image](https://user-images.githubusercontent.com/61829821/164886276-1a3216d0-8e1b-427d-912c-e482fb2de698.png)
I want to close the collector but using the API to report an error is weird.

**Comment by bcemmett** [comment]
I don't really follow what you're saying here, but it looks like you aren't using this library - I think you're using postman to talk to the api directly. This github project is just a library to use the api from .NET code - it isn't managed by surveymonkey.

That said, you're trying to make an api call, and there's a problem with it, so the api is giving you an error saying so - that's what it has to do. You can read the error message - it thinks you aren't on the right plan to do what you're asking. Probably that's because, in your request body, as well as changing it to closed (ln 3), you're also trying to set a thank you message (ln 4), custom disqualification message (ln 5), and redirect url (ln 7). All of those require a paid plan, so the api is telling you that your plan doesn't let you do that. If you removed those lines in the request body and purely set status to closed, that may be what you need.

**Comment by dickens1998** [comment]
Thank you for your reply. I seem to have succeeded through your explanation.

**Comment by bcemmett** [comment]
Cool, glad it works.
